metadata:
  name: demo-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=simonettifr/gitops-demo
    argocd-image-updater.argoproj.io/app.update-strategy: semver
    argocd-image-updater.argoproj.io/app.allow-tags: regexp:^1\..*
    argocd-image-updater.argoproj.io/write-back-method: git
